//! Deploy Targets — Layer 1 data model.
//!
//! A Deploy Target is a stored connection to a hosting platform (Vercel,
//! Railway, or a generic SSH/VPS) that the agent can use to ship the current
//! workspace to production via the `Deploy` tool (Layer 2, option C).
//!
//! Structurally this mirrors [`crate::mcp::McpSettings`]: a flat list of
//! configs, each carrying an `enabled` flag. Secrets (`token`) are stored in
//! clear text alongside the rest of the config, consistent with how
//! [`crate::store::ToolSettings`] already persists `database_password`,
//! `supabase_key`, etc. There is no OS keychain integration today.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sinew_core::ToolDescriptor;

use crate::tool_run::ToolRunResult;

/// Public name of the deploy tool exposed to the model (Layer 2).
pub const DEPLOY_TOOL_NAME: &str = "Deploy";

/// Persisted set of deploy targets. Serialized under the `deploy_settings`
/// key in the app settings store.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeploySettings {
    #[serde(default)]
    pub targets: Vec<DeployTarget>,
}

impl DeploySettings {
    /// Normalize all targets (trim strings) in place.
    pub fn sanitize(&mut self) {
        for target in &mut self.targets {
            target.sanitize();
        }
    }

    /// Iterator over the targets the agent is allowed to use.
    pub fn enabled_targets(&self) -> impl Iterator<Item = &DeployTarget> {
        self.targets.iter().filter(|target| target.enabled)
    }

    /// Resolve a target by id, falling back to the first enabled one when no
    /// id is provided (the agent usually just says "deploy").
    pub fn resolve<'a>(&'a self, id: Option<&str>) -> Option<&'a DeployTarget> {
        match id.map(str::trim).filter(|value| !value.is_empty()) {
            Some(id) => self
                .targets
                .iter()
                .find(|target| target.enabled && target.id == id),
            None => self.enabled_targets().next(),
        }
    }
}

/// Supported deploy platforms. Layer 2 wires Vercel first; Railway and Ssh are
/// modeled now so the UI and persistence are stable, and only get their command
/// builders filled in later.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DeployPlatform {
    Vercel,
    Railway,
    Ssh,
}

impl DeployPlatform {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Vercel => "vercel",
            Self::Railway => "railway",
            Self::Ssh => "ssh",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "vercel" => Some(Self::Vercel),
            "railway" => Some(Self::Railway),
            "ssh" | "vps" => Some(Self::Ssh),
            _ => None,
        }
    }
}

impl Default for DeployPlatform {
    fn default() -> Self {
        Self::Vercel
    }
}

/// Which environment a deploy targets by default. Production deploys are the
/// ones that trigger the per-call confirmation guardrail in Layer 2.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DeployEnvironment {
    Preview,
    #[default]
    Production,
}

impl DeployEnvironment {
    pub fn is_production(self) -> bool {
        matches!(self, Self::Production)
    }
}

/// A single configured deploy target.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeployTarget {
    /// Stable identifier (UUID generated by the front-end on creation).
    pub id: String,
    /// Human-readable label shown in the UI.
    pub name: String,
    pub platform: DeployPlatform,
    /// Auth token (Vercel / Railway). Stored in clear text. Unused for `Ssh`.
    #[serde(default)]
    pub token: String,
    /// Optional project / service identifier (Vercel project, Railway service).
    #[serde(default)]
    pub project: String,
    /// Default environment for this target.
    #[serde(default)]
    pub environment: DeployEnvironment,
    /// `user@host` for `Ssh` targets. Unused otherwise.
    #[serde(default)]
    pub host: String,
    /// Remote deploy command for `Ssh` targets (run over ssh). Unused otherwise.
    #[serde(default)]
    pub command: String,
    /// When true, a production deploy must be confirmed per call (Layer 2).
    #[serde(default = "default_require_confirmation")]
    pub require_confirmation: bool,
    /// When false, the target is hidden from the agent.
    #[serde(default = "default_enabled")]
    pub enabled: bool,
}

impl DeployTarget {
    fn sanitize(&mut self) {
        self.id = self.id.trim().to_string();
        self.name = self.name.trim().to_string();
        self.token = self.token.trim().to_string();
        self.project = self.project.trim().to_string();
        self.host = self.host.trim().to_string();
        self.command = self.command.trim().to_string();
    }

    /// True when the target has the minimum config needed to attempt a deploy.
    pub fn is_configured(&self) -> bool {
        match self.platform {
            DeployPlatform::Vercel | DeployPlatform::Railway => !self.token.is_empty(),
            DeployPlatform::Ssh => !self.host.is_empty() && !self.command.is_empty(),
        }
    }
}

fn default_require_confirmation() -> bool {
    // Frictionless by default: "deploy when I tell you" goes straight through.
    // Users opt into the guardrail per target.
    false
}

fn default_enabled() -> bool {
    true
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct DeployInput {
    #[serde(default)]
    target: Option<String>,
    #[serde(default)]
    environment: Option<String>,
    #[serde(default)]
    confirm: bool,
}

/// The `Deploy` tool (Layer 2, option C): a thin orchestrator over the platform
/// CLIs (`vercel`, `railway`, `ssh`). It never reimplements a platform API; it
/// just runs the right command with the target's secret injected as an env var.
pub struct DeployTool {
    targets: Vec<DeployTarget>,
    workspace_root: PathBuf,
}

impl DeployTool {
    pub fn new(targets: Vec<DeployTarget>, workspace_root: impl Into<PathBuf>) -> Self {
        Self {
            targets,
            workspace_root: workspace_root.into(),
        }
    }

    fn enabled(&self) -> Vec<&DeployTarget> {
        self.targets.iter().filter(|target| target.enabled).collect()
    }

    fn resolve(&self, key: Option<&str>) -> Option<&DeployTarget> {
        let enabled = self.enabled();
        match key.map(str::trim).filter(|value| !value.is_empty()) {
            Some(key) => enabled
                .iter()
                .find(|target| target.id == key || target.name.eq_ignore_ascii_case(key))
                .copied(),
            None => enabled.into_iter().next(),
        }
    }

    pub fn descriptor(&self) -> ToolDescriptor {
        let enabled = self.enabled();
        let description = if enabled.is_empty() {
            "Deploy the current workspace to a hosting platform. No deploy target is configured yet — ask the user to add one in Settings > Deploy Targets before calling this tool.".to_string()
        } else {
            let list = enabled
                .iter()
                .map(|target| {
                    format!(
                        "- {} ({}, default {})",
                        target.name,
                        target.platform.as_str(),
                        if target.environment.is_production() {
                            "production"
                        } else {
                            "preview"
                        }
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!(
                "Deploy the current workspace to a configured hosting target by running its platform CLI. Call this when the user asks to deploy/ship/publish.\n\nConfigured targets:\n{list}\n\nPass `target` (name or id) to pick one, or omit it to use the first enabled target. Pass `environment` (preview|production) to override the target default. A production deploy on a target that requires confirmation is refused unless you pass `confirm: true` — ask the user first in that case."
            )
        };
        ToolDescriptor {
            name: DEPLOY_TOOL_NAME.to_string(),
            description,
            input_schema: json!({
                "type": "object",
                "properties": {
                    "target": {
                        "type": "string",
                        "description": "Name or id of the deploy target. Omit to use the first enabled target."
                    },
                    "environment": {
                        "type": "string",
                        "enum": ["preview", "production"],
                        "description": "Override the target's default environment."
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Set true to confirm a production deploy on a target that requires confirmation."
                    }
                },
                "additionalProperties": false
            }),
        }
    }

    pub async fn run(&self, input: Value) -> ToolRunResult {
        let parsed: DeployInput = match serde_json::from_value(input) {
            Ok(value) => value,
            Err(err) => {
                return ToolRunResult::err(format!("invalid Deploy input: {err}"), Vec::new())
            }
        };

        let Some(target) = self.resolve(parsed.target.as_deref()) else {
            return ToolRunResult::ok(
                "No deploy target configured. Add one in Settings > Deploy Targets.".to_string(),
                Vec::new(),
            );
        };

        if !target.is_configured() {
            return ToolRunResult::ok(
                format!(
                    "Deploy target `{}` is incomplete. Finish its configuration in Settings > Deploy Targets.",
                    target.name
                ),
                Vec::new(),
            );
        }

        let production = match parsed.environment.as_deref().map(str::trim) {
            Some("production") | Some("prod") => true,
            Some("preview") => false,
            Some(other) if !other.is_empty() => {
                return ToolRunResult::err(
                    format!("invalid environment `{other}` (expected preview|production)"),
                    Vec::new(),
                )
            }
            _ => target.environment.is_production(),
        };

        if production && target.require_confirmation && !parsed.confirm {
            return ToolRunResult::ok(
                format!(
                    "⚠️ PRODUCTION deploy to `{}` ({}) requires confirmation. Confirm with the user, then re-call Deploy with confirm=true.",
                    target.name,
                    target.platform.as_str()
                ),
                Vec::new(),
            );
        }

        let (command, envs) = match build_deploy_command(target, production) {
            Ok(pair) => pair,
            Err(message) => return ToolRunResult::err(message, Vec::new()),
        };

        match run_shell_command(&command, &envs, &self.workspace_root).await {
            Ok((code, output)) => {
                let body = format!(
                    "Deploy `{}` ({}, {}) — exit {}\n$ {}\n\n{}",
                    target.name,
                    target.platform.as_str(),
                    if production { "production" } else { "preview" },
                    code,
                    command,
                    output.trim_end()
                );
                if code == 0 {
                    ToolRunResult::ok(body, Vec::new())
                } else {
                    ToolRunResult::err(body, Vec::new())
                }
            }
            Err(err) => ToolRunResult::err(format!("Deploy failed to start: {err}"), Vec::new()),
        }
    }
}

/// Build the shell command and env vars for a target. Secrets are passed via
/// env (`VERCEL_TOKEN` / `RAILWAY_TOKEN`), never inlined into the command
/// string, so the command can be echoed back safely.
fn build_deploy_command(
    target: &DeployTarget,
    production: bool,
) -> Result<(String, Vec<(String, String)>), String> {
    match target.platform {
        DeployPlatform::Vercel => {
            let mut command = String::from("vercel deploy --yes");
            if production {
                command.push_str(" --prod");
            }
            Ok((command, vec![("VERCEL_TOKEN".into(), target.token.clone())]))
        }
        DeployPlatform::Railway => {
            let mut command = String::from("railway up --ci");
            if !target.project.is_empty() {
                command.push_str(&format!(" --service {}", target.project));
            }
            Ok((command, vec![("RAILWAY_TOKEN".into(), target.token.clone())]))
        }
        DeployPlatform::Ssh => {
            if target.host.is_empty() || target.command.is_empty() {
                return Err("SSH target requires both a host and a deploy command".to_string());
            }
            Ok((format!("ssh {} {}", target.host, target.command), Vec::new()))
        }
    }
}

async fn run_shell_command(
    command: &str,
    envs: &[(String, String)],
    cwd: &Path,
) -> std::io::Result<(i32, String)> {
    use tokio::process::Command;

    let mut cmd = if cfg!(windows) {
        let mut c = Command::new("cmd");
        c.arg("/C").arg(command);
        c
    } else {
        let mut c = Command::new("sh");
        c.arg("-lc").arg(command);
        c
    };
    cmd.current_dir(cwd);
    cmd.env("NO_COLOR", "1");
    for (key, value) in envs {
        cmd.env(key, value);
    }

    let output = cmd.output().await?;
    let code = output.status.code().unwrap_or(-1);
    let mut text = String::from_utf8_lossy(&output.stdout).into_owned();
    let stderr = String::from_utf8_lossy(&output.stderr);
    if !stderr.trim().is_empty() {
        if !text.is_empty() {
            text.push('\n');
        }
        text.push_str(&stderr);
    }
    Ok((code, text))
}
